version: '2'

services:
    watcher-transilien:
        image: traincat/watcher-transilien:v2.2.0
        container_name: watcher-transilien
        external_links:
            - redis-watcher
        volumes:
                - "./config:/config:ro"
        networks:
            - redis-watcher

networks:
    redis-watcher:
        external: true

