version: '3'

services:
    app:
        image: traincat/cards-generator:v1.1.0
        container_name: cards-generator
        labels:
            - "traefik.backend=cards-generator"
            - "traefik.frontend.rule=Host:cards-generator.train.cat"
            - "traefik.port=8080"
            - "traefik.docker.network=reverse-proxy"
            - "traefik.enable=true"
        volumes:
            - "./config/app/config.json:/config.json:ro"
        networks:
            - reverse-proxy

networks:
    reverse-proxy:
        external: true

