version: '2'

services:
    redis:
        image: redis:4-alpine
        container_name: redis-watcher
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - "./data/redis:/data"
        networks:
            - redis-watcher

networks:
    redis-watcher:
        external: true

