version: '3'

services:
    app:
        image: traincat/api-train:v1.1.3
        container_name: api-train
        env_file: "./config/env"
        external_links:
            - mysql
        labels:
            - "traefik.backend=api-train"
            - "traefik.frontend.rule=Host:api.train.cat"
            - "traefik.port=80"
            - "traefik.docker.network=reverse-proxy"
            - "traefik.enable=true"
        networks:
            - mysql
            - reverse-proxy

networks:
    mysql:
        external: true
    reverse-proxy:
        external: true

