version: '2'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=<password>
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/mysql:/etc/mysql/conf.d:ro
        labels:
            - "traefik.enable=false"
        networks:
            - mysql

networks:
    mysql:
        external: true

